### PR TITLE
[0.x] Test on PHP 7.3

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Looks like PHP 7.4 is not working on 0.x, but was fixed on 1.x. We should still test on PHP 7.3, though.

**Comment by GrahamCampbell** [comment]
The test failures seem unrelated.

**Comment by jaapio** [comment]
Yes they are, it is ok to merge this.

**Comment by jaapio** [comment]
Thanks!

**Comment by GrahamCampbell** [comment]
🚀

**Pull request merged**
