### PR TITLE
add support for phpstan/phpdoc-parser 2

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Review by jaapio — CHANGES_REQUESTED** [review]
Thanks a lot for your help to upgrade, I think we should accept the issues in the pipeline by adding the phpstan errors to the baseline. And add the missing symbol to the composer-require-checker config. 

Let me know if you need any help with that.

**Comment by xabbuh** [comment]
@jaapio thanks for the feedback, I guess this should be good now

**Review by jaapio — APPROVED** [review]

**Comment by jaapio** [comment]
Merged and a new tag has been created. Thanks for your help

**Comment by xabbuh** [comment]
Thank you for the fast release! 👍

**Pull request merged**
