### PR TITLE
Psalm: Enable totallyTyped=true and bump type coverage to 100%

### PR DESCRIPTION
**Pull request by orklah**
This PR enforce a little more checks with Psalm

I had to ignore three errors. Two have the same cause: the library doesn't always check ArrayIterator::valid() before calling ArrayIterator::current so it can get a null value. This is not expected by Psalm. It's sort of false positive but caused by a bad practice...

The third I think is legitimate but I didn't take the time to prove it so I'll ignore it for now.

### CODE REVIEW

**Comment by orklah** [comment]
Arg, I don't get the same result locally than on CI. I think we have an old version of Psalm in CI and it's missing some important elements.

@jaapio Would you mind bumping Psalm?

**Comment by jaapio** [comment]
I will have a look at how to fix this.

**Comment by jaapio** [comment]
I upgrade psalm, will fix the build on master when needed. But I expect it to pass.

**Comment by orklah** [comment]
Cool, thanks!

**Pull request merged**
