### PR TITLE
Pseudo keywords as "scalar", "mixed" etc should be check case sensitive

### PR DESCRIPTION
**Pull request by kukulich**
Fix of https://github.com/phpDocumentor/TypeResolver/issues/43

### CODE REVIEW

**Comment by jaapio** [comment]
Although I understand this case I'm wondering if this is the correct way of solving this issue. I think  we should try to discover the type first as a FQSEN if there is no FQSEN found keywords should be used. In other words. FQSEN should have a higher priority.

Theoretically this will happen either when you define a class equal to other keywords. This is not possible due php's implementation of keywords but situations are comparable.

**Comment by kukulich** [comment]
@jaapio Ok, I will try to prepare it.

**Comment by kukulich** [comment]
@jaapio Is it even possible?

```php
namespace Foo;

class Boo
{
    /**
     * @param Scalar $scalar
     */
    public function __construct($scalar)
    {
    }
}
```

I think you always have to resolve `Scalar` as class name because it can be class in the same namespace.

I think there are only two options:
1. `scalar` and `Scalar` always resolve as class name - `scalar` keyword could not be implemented then.
2. Make an assumption that only lowercased `scalar` is a keyword - class name `scalar` could not be resolved then.

**Comment by GrahamCampbell** [comment]
I'm not sure this is a good idea,  types in php are not case sensitive. The only way in which it may appear not to be the case is due to autoloading from a case sensitive filesystem, however, once the file is loaded, any case will work.

**Comment by ashnazg** [comment]
Comments on #43 indicate this was determined to not be feasible.

**Pull request closed without merging**
