### PR TITLE
TypeResolver - Ignore whitespaces around tokens

### PR DESCRIPTION
**Pull request by popy-dev**
This is an attempt to fix issue #49. While fixing it it appeared simpler to update the preg split pattern to match (and ignore) whitespaces everywhere, which means following types will work : 

- array<int, string>
- array    <     int   ,    string    >

If it is too open, I can change that to only ignore one|all whitespace after the `,` token.

I also updated the PREG comment.

### CODE REVIEW

**Comment by ashnazg** [comment]
@popy-dev I think we *do* want you to restrict this to one space after comma, while not allowing for any additional spaces elsewhere.  Also, you may need to rebase against master to clear the conflict.

**Comment by ashnazg** [comment]
@popy-dev would also be good to adjust test cases to highlight instances of the extra spacing *not* being allowed.

**Comment by popy-dev** [comment]
Back from holidays, I'll have a look at this soon. Thanks for feedback !

**Comment by popy-dev** [comment]
Maybe i should have answered there after I submitted fixes ?

Also, note that travis runs had bugs unrelated to the patch.

**Comment by jaapio** [comment]
Thanks for the update.I need to check this in detail. To see what is going on. And if all changes are needed.

**Comment by jaapio** [comment]
Thanks, this looks good.

**Comment by bendavies** [comment]
this change seems mostly pointless, as https://github.com/phpDocumentor/ReflectionDocBlock splits on whitespace when parsing out `@var` and `@return` tags: https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tags/Var_.php#L56
so for example, given `@var Collection<int, Foo>` `Collection<int` will be parsed to `TypeResolver::resolve`, which will then error.

**Comment by jaapio** [comment]
could be, but that needs to be fixed in the Docblock component.

**Pull request merged**
