### PR TITLE
Add support "&" separator

### PR DESCRIPTION
**Pull request by Big-Shark**
Hi, I think we need support  "&" separator.

https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#abnf

### CODE REVIEW

**Comment by Big-Shark** [comment]
@jaapio hmmm, something strange.

**Comment by jaapio** [comment]
This PR needs tests to ensure we don't break anything in the future. 

After those are added I will have a look what is going on with the CI

**Comment by Big-Shark** [comment]
@jaapio ok, thx, I will add tests today

**Comment by Big-Shark** [comment]
@jaapio Ohhh, we have a problem
https://github.com/phpDocumentor/TypeResolver/blob/master/src/Types/Compound.php#L90

I think we need to add compound type in the constructor, but I think we can have a problem with different compounds in one comment. What do you think about this?

**Comment by jaapio** [comment]
I think we have to check what is possible, because if you are mixing the `&` and `|` you will get a very complex type. you might need to add brackets to ensure you are defining the correct types? 

`classA|classB&ClassC` would result in multiple compounds? I think our current parser cannot handle all cases users might come up with. This will require more work, and even more, tests to ensure we have everything in place.

**Comment by Big-Shark** [comment]
@jaapio Please, check, I added a new type, but I am not sure about naming.
I wrote some hooks because I tried not to break BC.
If you have any ideas about this, please, write to me.

**Comment by jaapio** [comment]
Hi,

Thanks for your efforts so far. I need to have a better look at the changes you did to understand what is changed. I don't have time for that right now. But I do hope that I will be able to review your changes soon. 

It would be very great if you are able to make all build steps pass except the profile step which is currently broken. If you need any help with that I'm available for questions.
Thanks a lot for your help!

**Comment by Big-Shark** [comment]
@jaapio Ok, I can try, but stan and psalm does not work too

**Comment by Big-Shark** [comment]
@jaapio Did you have time to check this?

**Comment by jaapio** [comment]
Thanks for this contribution. I will check the build status conce this has been merged.

**Comment by Big-Shark** [comment]
@jaapio Thanks

**Pull request merged**
