### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by orklah**
Some suggestions by PHP EA on PHPStorm

This introduce potentially some BC breaks (return type, final) but another one was committed on master already: https://github.com/phpDocumentor/TypeResolver/commit/3a0a285def1b123f198306e1d57576c04feb0dc9#diff-5bcf53cbf788ba443804c35c660f7182R95

We'll just have to make sure the next version is a major?

### CODE REVIEW

**Comment by orklah** [comment]
Apparently, return types are not considered BC breaks so I reverted final declaration

**Comment by jaapio** [comment]
Could you please rebase this PR?

**Comment by orklah** [comment]
Rebase is done. Profiling is failing for obscure reason

**Comment by jaapio** [comment]
Yeah I need to check the package I'm creating for this

**Pull request merged**
